categories:
  - title: '🌱 Growth Pod'
    labels:
      - 'Growth'
  - title: '💳 Credit Card Pod'
    labels:
      - 'Credit Card'
  - title: '🛍 Spend Pod'
    labels:
      - 'Spend'
  - title: '🛠 Platform Pod'
    labels:
      -  'Platform'
  - title: '📈 Invest/Borrow Pod'
    labels:
      - 'Invest'
      - 'Borrow'
  - title: 'Tech Debt/CI Improvements'
    labels:
      - 'Tech Debt'
template: $CHANGES
