changelog:
  sections:
  - title: "🌱 Growth Pod"
    labels: ["Growth"]
  - title: "💳 Credit Card Pod"
    labels: ["Credit Card"]
  - title: "🛍 Spend Pod"
    labels: ["Spend"]
  - title: "🛠 Platform Pod"
    labels: ["Platform"]
  - title: "🎉 Dash Pod"
    labels: ["Dash"]
  - title: "🦖 Velocity Pod"
    labels: ["Velocity"]
  - title: "📈 Invest/Borrow Pod"
    labels: ["Invest", "Borrow"]
  - title: "Tech Debt/CI Improvements"
    labels: ["Tech Debt"]
