# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :pullRequestCheck do
    # Install bundler
    sh("gem install bundler:2.2.11")

    # Install gem dependencies
    bundle_install

    # Install cocoapods
    cocoapods(
      repo_update: true,
      use_bundle_exec: true
    )

    # Build and run tests
    scan
  end
end
