# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :pullRequestCheck do
    # Install cocoapods
    cocoapods(repo_update: true)

    # Build and run tests
    scan
  end

  desc "Update version to value"
  lane :updateVersion do |options|
    increment_version_number(
      version_number: options[:version] # Set a specific version number
    )
  end
  
  desc "Release"
  lane :release do
    ensure_git_branch(branch: 'release-*.*.*')
  end
end
