name: Deploy to AppStore, Create Release, Version Bump

on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'phased_release or automatic_release'
        required: true
        default: 'automatic_release'
      nextVersion:
        description: 'Next version (ex. 2021.8.2)'
        required: true

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  buildTest:
    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundler Install
        run: gem install bundler:2.2.11
      
      - name: Bundle Install
        run: bundle install

      - name: Install Cocoapods
        run: bundle exec pod install --repo-update

      - name: Extract Release
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/release-})"

      - name: Print Release
        run: echo ${{ steps.extract_branch.outputs.branch }}
      
      - name: Create New Tag for Current Release
        # need to extract 2021.8.2 from refs/head/release-2021.8.2
        # create new tag with v2021.8.2
        run: |
          git tag v${{ steps.extract_branch.outputs.branch }}
          git push origin --tags

      - name: Deploy to App Store
        run: |
          echo "Simulating deploying to app store..."
          echo "Setting release to ${{ github.event.inputs.releaseType }}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.extract_branch.outputs.branch }}
          name: Release v${{ steps.extract_branch.outputs.branch }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Develop
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Create Version Bump 
        run: bundle exec fastlane increment_version_number --version_number ${{ github.event.inputs.nextVersion }}

      - name: Create Version Bump Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'automated-${{ github.event.inputs.nextVersion }}-version-bump'

      - name: Merge Version Bump Branch
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'automated-${{ github.event.inputs.nextVersion }}-version-bump'
          target_branch: 'develop'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'