name: Get merge events
on:
  pull_request:
    types: [closed]

jobs:
  create-merge-comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Event
        run: echo ${{ toJson(github) }}
