name: Build and run local unit tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches-ignore:
      - develop
      - release-*.*.*

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  buildTest:
    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundler Install
        run: gem install bundler:2.2.11
      
      - name: Bundle Install
        run: bundle install

      - name: Install Cocoapods
        run: bundle exec pod install --repo-update
      
      - name: Build and run unit tests
        run: bundle exec fastlane pullRequestCheck
