name: Build, Test, Testflight DEV

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: 
      - 'staging'

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  clearPreviousRuns:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  buildTest:
    needs: clearPreviousRuns

    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundler Install
        run: gem install bundler:2.2.11
      
      - name: Bundle Install
        run: bundle install

      - name: Install Cocoapods
        run: bundle exec pod install --repo-update
      
      - name: Build and run unit tests
        # run: bundle exec fastlane pullRequestCheck
        run: echo "Simulating building and running tests..."

      - name: Deploy to Test Flight
        if: contains(github.event.pull_request.labels.*.name, 'Build')
        run: echo "Simulating test flight deployment..."
