name: Build, Test, TestFlight DEV

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [ labeled ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  buildTestDeploy:
    if: ${{ github.event.label.name == 'Build' }}
    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundler Install
        run: gem install bundler:2.2.11
      
      - name: Bundle Install
        run: bundle install

      - name: Install Cocoapods
        run: bundle exec pod install --repo-update
      
      - name: Build and run unit tests
        run: bundle exec fastlane pullRequestCheck
        
      - name: Deploy to Testflight Dev
        run: echo "Simulating deploying to Testflight...."
