name: Pull Request Check

on:
  pull_request:
    branches-ignore: [ release ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  clearPreviousRuns:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  buildTest:
    needs: clearPreviousRuns

    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and run unit tests
        # run: bundle exec fastlane pullRequestCheck
        run: echo "Simulating building and running tests..."
      
      - name: Print ref
        run: echo ${{ github.ref }}
