name: Build and run local unit tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches-ignore:
      - develop
      - release-*.*.*

jobs:
  buildTest:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: "/Applications/Xcode_12.5.1.app"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update dependencies
        run: |
          gem install bundler:2.2.11
          bundle install
          bundle exec pod install --repo-update
      
      - name: Build and run unit tests
        run: bundle exec fastlane pullRequestCheck
