name: Build, Testflight DEV, Testflight PROD

on:
  workflow_dispatch:
  
  push:
    branches:
      - release-*.*.*

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  buildTest:
    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build and run unit tests
        # run: bundle exec fastlane pullRequestCheck
        run: echo "Simulating building and running tests..."

      - name: Deploy to Test Flight DEV
        run: echo "Simulating test flight deployment..."

      - name: Deploy to Test Flight PROD
        run: echo "Simulating test flight deployment to app store connect..."

      - name: Print ref
        if: ${{ startsWith(github.ref, 'refs/heads/release-') }}
        run: echo ${{ github.ref }}
        
      - name: Test ensure branch
        run: fastlane release

