name: Build, Testflight DEV, Testflight PROD

on:
  push:
    branches:
      - release-*.*.*

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  buildTest:
    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundler Install
        run: gem install bundler:2.2.11
      
      - name: Bundle Install
        run: bundle install

      - name: Install Cocoapods
        run: bundle exec pod install --repo-update
      
      - name: Build and run unit tests
        run: bundle exec fastlane pullRequestCheck

      - name: Deploy to Test Flight DEV
        run: echo "Simulating test flight deployment..."

      - name: Deploy to Test Flight PROD
        run: echo "Simulating test flight deployment to app store connect..."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
          with: 
            branch: "automated-mergeback"
            branch-suffix: "timestamp"
            title: "Automated - Mergeback"
            body: "This is an automated branch. Check out and resolve any conflicts if needed."
            labels: "Automated"
            delete-branch: true
            base: "develop"

