# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
name: Milestone Release Notes
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes

      - name: Output Release Notes
        id: release_notes_job
        run: |
          RAW_RELEASE_NOTES=$(cat temp_release_notes/release_file.md)
          echo "::set-output name=RELEASE_NOTES::$RAW_RELEASE_NOTES"

      - name: Echo 
        run: echo ${{ steps.release_notes_job.outputs.RELEASE_NOTES }}

#       - name: Post to Slack
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#           SLACK_MESSAGE: ```\n${{ steps.release_notes_job.outputs.RELEASE_NOTES }}\n```
#           SLACK_TITLE: "Release Notes"
      
