name: Build, Testflight DEV, Testflight PROD

on:
  workflow_dispatch:
    inputs:
      updatedReleaseNotes:
          description: 'Release notes to use for submission. If empty, will use `fastlane/metadata/default/release_notes.txt`'
          required: false
  
  push:
    branches:
      - release-*.*.*

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  buildTest:
    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build and run unit tests
        # run: bundle exec fastlane pullRequestCheck
        run: echo "Simulating building and running tests..."

      - name: Deploy to Test Flight DEV
        run: echo "Simulating test flight deployment..."

      - name: Deploy to Test Flight PROD
        run: echo "Simulating test flight deployment to app store connect..."

      - name: Update Release Notes If Needed
        if: ${{ github.event.inputs.updatedReleaseNotes }}
        run: echo ${{ github.event.inputs.updatedReleaseNotes }} > fastlane/metadata/default/release_notes.txt
        
      - name: Print release notes
        run: cat fastlane/metadata/default/release_notes.txt
        
