name: Create Release Notes

# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        name: $(/JSON.sh < "${GITHUB_EVENT_PATH}" | grep '\["milestone","title"]' | cut -f2 | sed 's/\"//g' | sed 's/ /_/g')
        bodyFile: temp_release_notes/release_file.md
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/upload-artifact@v2
      with:
        path: temp_release_notes/release_file.md
