name: Create Release Notes

# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
    - uses: actions/upload-artifact@v2
      with:
        path: temp_release_notes/release_file.md
