name: Create Release Notes

# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        
    - name: Output Release Notes
      id: release_notes_job
      run: echo ::set-output name=RELEASE_NOTES::$(cat ci_release_notes/RELEASE_NOTES.md)
      
    - name: Echo
      run: echo ```\n${{ steps.release_notes_job.outputs.RELEASE_NOTES }}\n```
